--- 
trigger_media:
  extends: .trigger_down_stream
  trigger:
    project: npo/media
    branch: master

include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/5.7'
    file: 'maven_release.yml'
