---
variables:
  PUBLISH_ARTIFACTS_OF_MERGE_REQUESTS: 'true' # This project normally is just developed by one person, so just publish the merge requests, so we can more easily deploy features


trigger_media:
  extends: .trigger_down_stream
  trigger:
    project: npo/media
    branch: $CI_COMMIT_BRANCH
  rules: !reference[.rules, build]



include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/9.18'
    file: 'maven_release.yml'
