stages:
  - build
  - package
  - validate
  - release

include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/1.11'
    file: 'java_maven.yml'
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/1.11'
    file: 'maven_release.yml'
