---
stages:
  - build
  - publish
  - validate
  - release

trigger_media:
  extends: .trigger_down_stream
  trigger:
    project: npo/media
    branch: master

include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'main'
    file: 'maven_release.yml'
