---
variables:
  PUBLISH_ARTIFACTS_OF_MERGE_REQUESTS: 'true' # This project normally is just developed by one person, so just publish the merge requests, so we can more easily deploy features
  SKIP_TESTS_IMPLICIT: 'true' # no (java) tests in this project.
  MAVEN_IMAGE: 'ghcr.io/vpro/maven:main'




trigger_media:
  extends: .trigger_down_stream
  trigger:
    project: npo-identity/poms/media
    branch: main

include:
  - project: 'npo-identity/poms/gitlab-templates'
    ref: "tags/12.21"
    file: 'maven_release.yml'
