---
name: release
run-name: Creating release by ${{ github.actor }} on ${{ github.ref_name }}
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    if: startsWith(github.ref, 'refs/heads/REL-')
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: maven
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          server-id: 'github'
      - name: Prepare and perform Release
        run: |
          git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=${{ secrets.GITHUB_TOKEN }}"; }; f'
          git remote -v
          git config --global user.name "github $GITHUB_ACTOR"
          git config --global user.email "poms@mmprogrami.nl"

          git remote -v
          mvn -U --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn  --batch-mode -Darguments=-DskipTests release:perform
        env:
         MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

